config/routes.rb
Rails.application.routes.draw do
  root to: 'web_scrapers#new'
  resources :web_scrapers,  only: [ :index, :new, :create, :destroy]

  devise_for :users, controllers: { sessions: 'users/sessions' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/web_scrape.rb
class WebScrape < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/web_scrapers_controller.rb
class WebScrapersController < ApplicationController
	def index
		@web_scrapes = WebScrape.all
	end

	def new
		@web_scrape = WebScrape.new
	end

	def create
		split_urls = params[:web_scrape][:url].gsub(/\s+/, "").split(',')
		split_urls.each do |url|
			make_valid_url(url)
		end
		redirect_to web_scrapers_path
	end

	def destroy
		@web_scrape = WebScrape.find(params[:id])
		@web_scrape.destroy

		redirect_to web_scrapers_path
	end

	private

		def make_valid_url(url)
			u = URI.parse(url)
			if(%w{http https}.include?(u.scheme))
				get_infromation_from_url(url)
			else
				url.insert(0, 'http://')
			    get_infromation_from_url(url)
			end
		end

		def get_infromation_from_url(url)
			OpenURI.redirect_to_https = true 
			begin
				doc = Pismo::Document.new(url)
				if doc.present?
					title = doc.title.present? ? doc.title : "Invalid URL"
					# favicon = doc.favicon.present? ? doc.favicon : "Invalid URL"
					scrape = WebScrape.new(url: url, title: title)
					scrape.remote_avatar_url = doc.favicon if doc.favicon.present?
					scrape.save
				end
			rescue OpenURI::HTTPError => error
				response = error.io
				flash[:notice] = "#{response.status} for the #{url}"
			end    

		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/web_scrapers_helper.rb
module WebScrapersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PunchTask</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% flash.each do |type, message| %>
      <div class="flash">
        <%= message %>
      </div>        
    <% end %> 
    <header>
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">Punch Task App</a>
          </div>
          <div id="navbar" class="collapse navbar-collapse">
          <% if user_signed_in? %>
            <ul class="nav navbar-nav">
              <li class="active"><%= link_to "List",web_scrapers_path %></li>
            </ul>
            <ul class="nav navbar-nav">
              <li class="active"><%= link_to "Add New",new_web_scraper_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to 'Sign-Out', destroy_user_session_path,
                    method: :delete %></li>
            </ul> 
          <% end %>
          </div><!--/.nav-collapse -->
        </div>
      </nav>  
    </header>
    <%= yield %>
    <footer class="site-footer">
    </footer>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/web_scrapers/index.html.erb
<h1>Listing URLs with Information</h1>
 
<table>
  <tr>
    <th>Url</th>
    <th>Title</th>
    <th>Favicon</th>
  </tr>
 
  <% @web_scrapes.each do |record| %>
    <tr>
      <td><%= record.url %></td>
      <td><%= record.title %></td>
      <td>
        <%if record.avatar.url.present? %>
          <%= image_tag(record.avatar.url(:thumb),class: 'img-responsive') %></td>
        <%else%>
          <%= image_tag("default.jpg", :size => "50x50") %>
        <% end %> 
      <td><%= link_to 'Delete', web_scraper_path(record),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/web_scrapers/new.html.erb
<h3>Enter mutlipe URLs with seprating ,</h3>
<%= form_for @web_scrape, url: web_scrapers_path, html: {class: 'form-horizontal'} do |f| %>
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>
 
  <p>
    <%= f.submit "Submit" %>
  </p>
<% end %>